server:
  port: 8000   #ע�����Ķ˿���8001

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chouxin/spring-cloud-config-repo/   #githubcong��Ŀ
          search-paths: config-repo
          username: 342175867@qq.com
          password: xxxx
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/